title: render-vendor
description: "render-vendor is the fastest way to render HTML documents to PDFs"
author: Isle of Code
url: "http://render-vendor.com"
baseurl: ''
twitter_username: isleOfCode
github_username:  isleOfCode
language: en_US
permalink: none
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
